# Generated by Django 2.2.4 on 2019-09-02 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippet',
            old_name='owmer',
            new_name='owner',
        ),
    ]
